import type { Metadata } from 'next';
import { Be_Vietnam_Pro } from 'next/font/google';
import Header from './components/header/Header';

import './globals.css';

const inter = Be_Vietnam_Pro({
  weight: ['200', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Unsplash Collection',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
